/**
 * The health line, and the reason it stopped being typed.
 *
 * `docs/status.md` opened with "4,553 archived · 4,417 published · 136 refused ·
 * 567 JS + 130 Python tests" and every number was wrong within a day — twice.
 * It even carried a warning saying so, which is a disclaimer standing where an
 * invariant belongs. These tests cover the two things the generator can get
 * wrong QUIETLY: inventing a figure it could not read, and formatting a block
 * whose numbers no longer match the suite that produced them.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { block } from '../builders/health.mjs';

const LIVE = { games: 4553, published: 4490, refused: 63, unreconciled: 73,
               asOf: '2026-08-21T15:07:34Z' };

test('the block carries the figures it was handed, with thousands separators', () => {
  const b = block({ js: 608, py: 148 }, LIVE, '2026-08-21');
  assert.match(b, /4,553 archived/);
  assert.match(b, /\*\*4,490 published\*\*/);
  assert.match(b, /63 refused/);
  assert.match(b, /\*\*608 JS \+ 148 Python tests\*\*/);
});

test('⭐ no network is a STATE, not a zero', () => {
  // "We could not ask" and "the archive is empty" are different sentences and
  // only one of them is alarming. A generator that printed 0 archived would be
  // the most alarming possible way to say nothing happened.
  const b = block({ js: 608, py: 148 }, null, '2026-08-21');
  assert.match(b, /archive not read/);
  assert.doesNotMatch(b, /\b0 archived\b/);
  assert.doesNotMatch(b, /published/, 'it must not name a figure it never read');
  assert.match(b, /\*\*608 JS \+ 148 Python tests\*\*/, 'the half it CAN count survives');
});

test('an archive figure is stamped with when it was read', () => {
  // A figure with no date is the thing that misleads. The nightly moves these
  // with no deploy, so a committed copy is right only for as long as it is not
  // read — and the stamp is what tells a reader which case they are in.
  const b = block({ js: 608, py: 148 }, LIVE, '2026-08-21');
  assert.match(b, /Generated 2026-08-21/);
  assert.match(b, /asOf` is 2026-08-21T15:07:34Z/, "the LEDGER's own stamp, not ours");
});

test('a missing count degrades to a dash rather than to NaN', () => {
  // The first version read only stdout, and `unittest` reports "Ran N tests" on
  // stderr — so the generated line said "NaN Python tests" and looked deliberate.
  const b = block({ js: 608, py: null }, LIVE, '2026-08-21');
  assert.match(b, /— Python tests/);
  assert.doesNotMatch(b, /NaN/);
});

test('the shipped block is well formed and still delimited — NOT that it is current', () => {
  /* ⚠️ THIS TEST CANNOT SEE DRIFT, AND ITS FIRST NAME SAID IT COULD.
     It was called "agrees with the suite that is running right now" and it does
     not: a test inside `node --test` has no access to the run's own total, so
     all it can check is that the figure is present, parses, and is plausible.
     I set the doc back to 567/130 and the whole suite stayed green.

     That is the same overstatement `teams.js` was carrying — a check named for
     a guarantee it does not provide, which is worse than no check because it
     stops anyone building the real one. The real one is `npm run health
     --check`, which RUNS both suites and compares; it exits 1 on exactly the
     drift this cannot see, and `npm run gates` calls it.

     What this covers is the failure that would make that gate meaningless: a
     block that lost its markers or its formatting, after which the comparison
     has nothing to read. */
  const doc = readFileSync(new URL('../docs/status.md', import.meta.url), 'utf8');
  const said = doc.match(/\*\*([\d,]+) JS \+ ([\d,]+) Python tests\*\*/);
  assert.ok(said, 'docs/status.md has no generated health line');
  const js = Number(said[1].replace(/,/g, ''));
  assert.ok(js > 100, `implausible JS count in the health line: ${said[1]}`);
  assert.match(doc, /<!-- health: generated by builders\/health\.mjs/,
               'the block must stay delimited, or regeneration eats the document');
});
