/**
 * The learn page — every claim on it is a door into a real game.
 *
 * THE PAGE SHIPPED A FALSE SENTENCE. It ended with "every one of them is a
 * toggle on a real game" and carried zero links to any game; every href on it
 * was chrome. Nothing in the suite could see that, because the promise was
 * prose and the absence was of a thing nobody had asserted must exist.
 *
 * So these tests do not compare the page to a fixture of itself. They re-derive
 * every moment from data/rich.json through the SAME reducers the page's doors
 * were generated by, and they parse every link with the real parser. A card
 * that points at an event its own layer does not count is the defect this file
 * exists to catch, because that one has no visible symptom.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { parse } from '../src/lib/deeplink.js';
import { corsi } from '../src/lib/layers/corsi.js';
import { danger } from '../src/lib/layers/danger.js';
import { goaltending } from '../src/lib/layers/goaltending.js';
import { doors } from '../builders/learn-doors.mjs';

const rich = JSON.parse(readFileSync(new URL('../data/rich.json', import.meta.url)));
const built = JSON.parse(readFileSync(new URL('../data/learn-doors.json', import.meta.url)));
const html = readFileSync(new URL('../src/what-you-can-see.html', import.meta.url), 'utf8');

const CTX = { homeId: rich.teams.home.id, awayId: rich.teams.away.id,
              roster: rich.roster, evenOnly: false };

/** The cards as the page actually renders them, in document order. */
const cards = [...html.matchAll(
  /<a class="card" href="([^"]+)"><p class="t">([^<]+)<\/p>/g)]
  .map(m => ({ href: m[1].replace(/&amp;/g, '&'), title: m[2] }));

/** The href a card carries, minus the page, as parse() wants it. */
const query = h => h.slice(h.indexOf('?'));

test('the page carries a door for every card, and they are real links', () => {
  // The old page had NONE. A count of zero is the failure this whole file is
  // about, so it is asserted before anything subtler.
  assert.ok(cards.length >= 9, `only ${cards.length} cards carry a game link`);
  for (const c of cards) {
    assert.ok(c.href.startsWith('/game.html?'),
              `"${c.title}" links to ${c.href}, which is not the app`);
  }
});

test('every door parses — through the real parser, with nothing to complain about', () => {
  for (const c of cards) {
    const p = parse(query(c.href));
    assert.deepEqual(p.problems, [], `"${c.title}" -> ${c.href}`);
    // parse() returns the id as a STRING and the extract carries it as a
    // NUMBER. Both are right in their own context and `===` across them is
    // false; this comparison coerces on purpose, and says so, because the
    // author of this file wrote that bug first.
    assert.equal(String(p.game), String(rich.game.id),
                 `"${c.title}" points at a different game`);
    assert.ok(p.at, `"${c.title}" names no moment`);
  }
});

test('every door lands on a moment the game actually contains', () => {
  for (const c of cards) {
    const { at } = parse(query(c.href));
    const hits = rich.events.filter(e => e.per === at.per && e.rem === at.rem);
    assert.ok(hits.length >= at.n,
              `"${c.title}" asks for occurrence ${at.n} at P${at.per} ${at.rem}, `
              + `and the game has ${hits.length}`);
  }
});

test('a measurement door is an event its own layer counts', () => {
  // THE DEFECT WITH NO SYMPTOM. "First event of the right type" sent the slot
  // card to a point shot at x=29 that the slot layer does not count -- and that
  // one was visible. Three cards landing on a single event was the same bug and
  // showed nothing at all. The rule is therefore asserted against the reducer,
  // never against a remembered index.
  for (const [id, layer] of [['control', corsi], ['slot', danger],
                             ['goaltending', goaltending], ['blocked', corsi]]) {
    const counted = new Set(layer.reduce(rich.events, CTX).counted);
    const door = built.doors[id];
    const idx = rich.events.findIndex((e, i) =>
      e.per === door.per && e.rem === door.rem && counted.has(i)
      && (id !== 'blocked' || e.type === 'blocked-shot'));
    assert.ok(idx >= 0,
              `the ${id} door points at P${door.per} ${door.rem}, which that layer does not count`);
  }
});

test('the slot door is a shot the slot layer counts and Control alone would not distinguish', () => {
  // The specific regression: x=29 is an attempt and is NOT in the slot. If this
  // door ever coincides with the Control door again, the two cards are teaching
  // the same thing under different names.
  const slot = new Set(danger.reduce(rich.events, CTX).counted);
  const i = rich.events.findIndex((e, k) => slot.has(k));
  assert.equal(built.doors.slot.rem, rich.events[i].rem);
  assert.notEqual(built.doors.slot.rem, built.doors.control.rem,
                  'the slot card and the Control card must not be the same moment');
});

test('the icing and the faceoff it forces are one clock apart by ordinal', () => {
  // THE RELATIONSHIP, NOT EITHER HALF. Two tests each pinning its own literal
  // could both pass while the pair stopped being a pair. The teaching point of
  // these two cards is that they are the same instant.
  const ice = parse(query(cards.find(c => /Icing/.test(c.title)).href));
  const fo = parse(query(cards.find(c => /faceoff/i.test(c.title)).href));
  assert.equal(fo.at.per, ice.at.per, 'the restart is in the same period');
  assert.equal(fo.at.rem, ice.at.rem, 'and at the same clock');
  assert.ok(fo.at.n > ice.at.n, 'and later in the sequence at that clock');
});

test('the empty-net door names no layer, because the base view already shows it', () => {
  // An empty net is not a stoppage and `goaltending` counts shots a goalie
  // faced, so at a pulled-goalie moment its subject is not on the ice. The rink
  // gates the glyph on `sit`, which is the whole lesson with no apparatus.
  const p = parse(query(cards.find(c => /empty net/i.test(c.title)).href));
  assert.deepEqual(p.layers, [], 'the empty-net card must toggle nothing');
  const e = rich.events.find(x => x.per === p.at.per && x.rem === p.at.rem);
  assert.ok(e.sit && (e.sit[0] === '0' || e.sit[3] === '0'),
            `the moment must actually have a goalie pulled, and sit is ${e && e.sit}`);
});

test('the closing sentence counts the cards it is standing next to', () => {
  // PROSE THAT REFERS TO ANOTHER ELEMENT BY COUNT has a dependency nothing in a
  // text file can see, and this page has already broken exactly that way once.
  const note = /<p class="cnote">([\s\S]*?)<\/p>/.exec(html)[1];
  const total = Number(/These (\d+) moments/.exec(note)[1]);
  const first = Number(/and (\d+) of them/.exec(note)[1]);
  assert.equal(total, cards.length, 'the sentence must count the cards on the page');
  const inP1 = Object.values(built.doors).filter(d => d.per === 1).length;
  assert.equal(first, inP1, 'and the first-period claim must be the real one');
});

test('the two groups stay apart, and the measurements are the marked half', () => {
  // The split is the page's argument -- the league's rules against our
  // arithmetic -- and a uniform grid would flatten two kinds of claim into one.
  assert.match(html, /class="grid learn rules"/);
  assert.match(html, /class="grid learn ours"/);

  // NOT "a border-left exists" -- that passed while the accent was set to the
  // same colour as every other card's edge, which is no distinction at all. The
  // property is that the marked group differs, and that it differs USING THE
  // TOKEN THAT ALREADY MEANS "our claim" on this site, so a reader meets a
  // marker they have seen on `.limits` rather than a new one.
  const accent = /\.grid\.learn\.ours \.card\{border-left:[^}]*?(var\(--[a-z]+\))\}/.exec(html);
  assert.ok(accent, 'the measurement group must carry its own left edge');
  const limits = /\.limits li\{[^}]*?border-left:[^;]*?(var\(--[a-z]+\))/.exec(html);
  assert.ok(limits, 'the .limits accent should still be there to agree with');
  assert.equal(accent[1], limits[1],
               'the measurement group must reuse the token that already means "our claim"');
  const edge = /(?<!\.grid\.learn\.ours )\.card\{[^}]*?border:1px solid (var\(--[a-z]+\))/.exec(html);
  assert.notEqual(accent[1], edge && edge[1],
                  'an accent the same colour as the default edge distinguishes nothing');
});

test('the doors document is what the layers currently say', () => {
  // The committed JSON is a build artifact, and a stale one would let the page
  // and the layers disagree silently. npm run build:check diffs it; this proves
  // the regeneration is deterministic and driven by the real reducers.
  assert.deepEqual(doors(rich), built);
});

test('a card with no door fails the build rather than rendering a dead link', () => {
  // The seam between two documents keyed by a shared set of ids. Proven by
  // asking the generator for a game it cannot serve every card from.
  const stripped = { ...rich, events: rich.events.filter(e => e.rsn !== 'icing') };
  assert.throws(() => doors(stripped), /icing/,
                'a game with no icing must refuse to produce doors, not emit a broken one');
});
