/**
 * The learn page — every claim on it is a door into a real game.
 *
 * THE PAGE SHIPPED A FALSE SENTENCE. It ended with "every one of them is a
 * toggle on a real game" and carried zero links to any game; every href on it
 * was chrome. Nothing in the suite could see that, because the promise was
 * prose and the absence was of a thing nobody had asserted must exist.
 *
 * So these tests do not compare the page to a fixture of itself. They re-derive
 * every moment from data/rich.json through the SAME reducers the page's doors
 * were generated by, and they parse every link with the real parser. A card
 * that points at an event its own layer does not count is the defect this file
 * exists to catch, because that one has no visible symptom.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { parse } from '../src/lib/deeplink.js';
import { corsi } from '../src/lib/layers/corsi.js';
import { danger } from '../src/lib/layers/danger.js';
import { goaltending } from '../src/lib/layers/goaltending.js';
import { doors } from '../builders/learn-doors.mjs';
import { playable } from '../src/lib/layer.js';
import { icingRestarts } from '../src/lib/layers/whistle.js';

const rich = JSON.parse(readFileSync(new URL('../data/rich.json', import.meta.url)));
const built = JSON.parse(readFileSync(new URL('../data/learn-doors.json', import.meta.url)));
const html = readFileSync(new URL('../src/what-you-can-see.html', import.meta.url), 'utf8');

const CTX = { homeId: rich.teams.home.id, awayId: rich.teams.away.id,
              roster: rich.roster, evenOnly: false };

/** The cards as the page actually renders them, in document order.
 *  ⭐ THE ID IS CAPTURED, NOT TOLERATED. It became load-bearing on 2026-08-31:
 *  the work panel links back to `#<card-id>`, so a card without one is a dead
 *  link from the game, and a card whose id is not its door key is a link to the
 *  wrong lesson. Reading it here is what lets the next test say so. */
const raw = [...html.matchAll(
  /<a class="card" id="([^"]+)" href="([^"]+)"><p class="t">([^<]+)<\/p>/g)]
  .map(m => ({ id: m[1], href: m[2].replace(/&amp;/g, '&'), title: m[3] }));

/* ⭐ A DOOR MAY NOW BE TWO HOPS, AND THE CLAIM IS UNCHANGED.
 *
 * Kevin, 2026-08-31: *"I want the diagram in place of the game replay we
 * currently get when the offside card is clicked."* A card with a rule diagram
 * opens the diagram, and the diagram page carries "See it in a real game". So
 * the door did not close, it moved down a level -- and every assertion in this
 * file is still about where a card EVENTUALLY lands, which is what it was always
 * about. Weakening them to "a card links somewhere" would have been the easy
 * change and would have stopped checking the thing that matters.
 *
 * Resolving the hop here rather than in each test also means a diagram page that
 * lost its door fails EVERY door test, not just one. */
const hopProblems = [];
const cards = raw.map(c => {
  if (c.href.startsWith('/game.html?')) return c;
  const m = /^\/([a-z-]+)\.html$/.exec(c.href);
  if (!m) { hopProblems.push(`"${c.title}" links to ${c.href}, neither the app nor a rule page`); return c; }
  let page = '';
  try { page = readFileSync(new URL(`../src/${m[1]}.html`, import.meta.url), 'utf8'); }
  catch { hopProblems.push(`"${c.title}" opens ${c.href}, which is not a file we build`); return c; }
  const door = /<a class="rgo" href="([^"]+)"/.exec(page);
  if (!door) { hopProblems.push(`"${c.title}" opens ${c.href}, which carries no way through to a game`); return c; }
  return { ...c, href: door[1].replace(/&amp;/g, '&'), via: c.href };
});

/** The href a card carries, minus the page, as parse() wants it. */
const query = h => h.slice(h.indexOf('?'));

test('the page carries a door for every card, and they are real links', () => {
  // The old page had NONE. A count of zero is the failure this whole file is
  // about, so it is asserted before anything subtler.
  assert.deepEqual(hopProblems, [], 'a card leads somewhere that does not reach a game');
  assert.ok(cards.length >= 9, `only ${cards.length} cards carry a game link`);
  for (const c of cards) {
    assert.ok(c.href.startsWith('/game.html?'),
              `"${c.title}" links to ${c.href}, which is not the app`);
  }
  // AND THE HOP IS EXERCISED, or the resolver above is dead code that proves
  // nothing about the pages it is meant to be reading.
  assert.ok(cards.some(c => c.via), 'no card reaches its game through a rule page');
});

test('every door parses — through the real parser, with nothing to complain about', () => {
  for (const c of cards) {
    const p = parse(query(c.href));
    assert.deepEqual(p.problems, [], `"${c.title}" -> ${c.href}`);
    // parse() returns the id as a STRING and the extract carries it as a
    // NUMBER. Both are right in their own context and `===` across them is
    // false; this comparison coerces on purpose, and says so, because the
    // author of this file wrote that bug first.
    assert.equal(String(p.game), String(rich.game.id),
                 `"${c.title}" points at a different game`);
    assert.ok(p.at, `"${c.title}" names no moment`);
  }
});

test('every door lands on a moment the game actually contains', () => {
  for (const c of cards) {
    const { at } = parse(query(c.href));
    const hits = rich.events.filter(e => e.per === at.per && e.rem === at.rem);
    assert.ok(hits.length >= at.n,
              `"${c.title}" asks for occurrence ${at.n} at P${at.per} ${at.rem}, `
              + `and the game has ${hits.length}`);
  }
});

test('a measurement door is an event its own layer counts', () => {
  // THE DEFECT WITH NO SYMPTOM. "First event of the right type" sent the slot
  // card to a point shot at x=29 that the slot layer does not count -- and that
  // one was visible. Three cards landing on a single event was the same bug and
  // showed nothing at all. The rule is therefore asserted against the reducer,
  // never against a remembered index.
  for (const [id, layer] of [['control', corsi], ['slot', danger],
                             ['goaltending', goaltending], ['blocked', corsi]]) {
    const counted = new Set(layer.reduce(rich.events, CTX).counted);
    const door = built.doors[id];
    const idx = rich.events.findIndex((e, i) =>
      e.per === door.per && e.rem === door.rem && counted.has(i)
      && (id !== 'blocked' || e.type === 'blocked-shot'));
    assert.ok(idx >= 0,
              `the ${id} door points at P${door.per} ${door.rem}, which that layer does not count`);
  }
});

test('the slot door is a shot the slot layer counts and Control alone would not distinguish', () => {
  // The specific regression: x=29 is an attempt and is NOT in the slot. If this
  // door ever coincides with the Control door again, the two cards are teaching
  // the same thing under different names.
  const slot = new Set(danger.reduce(rich.events, CTX).counted);
  const i = rich.events.findIndex((e, k) => slot.has(k));
  assert.equal(built.doors.slot.rem, rich.events[i].rem);
  assert.notEqual(built.doors.slot.rem, built.doors.control.rem,
                  'the slot card and the Control card must not be the same moment');
});

test('⭐ the icing and the faceoff it forces are ONE FRAME, deliberately', () => {
  /* ⭐ KEVIN'S RULING, 2026-08-31: "the pairing between icing and the faceoff is
     the teaching moment, those should stay paired."
     This test used to assert `fo.at.n > ice.at.n` — "later in the sequence at
     that clock" — and that was FALSE the whole time. The ordinals differed
     because learn-doors counted occurrences over every event, including the
     stoppage; the app resolves them over the playable timeline, where the
     stoppage does not exist and both cards were the SAME frame. The claim moved
     to what is true: one moment, two lessons.
     ⭐ AND IT IS DERIVED FROM `restarts`, not from the doors agreeing with each
     other. Two hrefs matching proves only that they match; this asserts the
     frame they share is the face-off that this game's first icing actually
     forced, which is the thing being taught. */
  const ice = parse(query(cards.find(c => /Icing/.test(c.title)).href));
  const fo = parse(query(cards.find(c => /faceoff/i.test(c.title)).href));
  assert.deepEqual(fo.at, ice.at,
    'the icing and its restart are no longer the same moment — the pairing is the lesson');

  const CT = { homeId: rich.teams.home.id, awayId: rich.teams.away.id,
               homeAb: rich.teams.home.ab, awayAb: rich.teams.away.ab };
  const forced = icingRestarts(rich.events, CT)[0];
  assert.ok(forced, 'the reference game contains no icing at all');
  assert.equal(ice.at.per, forced.event.per, 'the shared frame is not the restart period');
  assert.equal(ice.at.rem, forced.event.rem, 'the shared frame is not the restart the icing forced');
  // AND THE HOP IS RECORDED rather than silent: the icing door names a stoppage
  // and lands on the frame after it.
  assert.equal(built.doors.icing.via, 'stoppage',
    'the icing door no longer records that it hopped off an unplayable event');
  assert.equal(built.doors.faceoffs.via, undefined,
    'the faceoffs door claims a hop it did not make');
});

test('⭐ every door is REACHABLE on the timeline the app actually plays', () => {
  /* ⚠️ THE GUARD THAT SHOULD HAVE CAUGHT ALL OF THIS, WITH THE RIGHT DENOMINATOR.
     "every door lands on a moment the game actually contains" counted matches
     over `rich.events` — every event, including the ones the replay drops. The
     app indexes into the PLAYABLE list. So a door asking for occurrence 2 at a
     clock with two raw events and one playable frame passed a test and clamped
     in production. Ask what a drift alarm's denominator is.
     ⭐ AND `type` MUST BE THE FRAME'S. The document recorded the type of the
     event the RULE matched — `stoppage`, `delayed-penalty` — for doors that open
     something else, so the committed artifact asserted something untrue about
     where it goes. */
  const PLAY = playable(rich.events);
  for (const c of raw) {
    const id = c.id;
    const door = built.doors[id];
    const at = parse(query(door.href)).at;
    const here = PLAY.filter(e => e.per === at.per && e.rem === at.rem);
    assert.ok(here.length >= (at.n || 1),
      `"${c.title}" asks for occurrence ${at.n || 1} at P${at.per} ${at.rem}, and the `
      + `replay has ${here.length} frame(s) there — the app will clamp somewhere else`);
    const landed = here[(at.n || 1) - 1];
    assert.equal(landed.type, door.type,
      `the ${id} door records type "${door.type}" and opens a ${landed.type}`);
  }
});

test('the empty-net door names no layer, because the base view already shows it', () => {
  // An empty net is not a stoppage and `goaltending` counts shots a goalie
  // faced, so at a pulled-goalie moment its subject is not on the ice. The rink
  // gates the glyph on `sit`, which is the whole lesson with no apparatus.
  const p = parse(query(cards.find(c => /empty net/i.test(c.title)).href));
  assert.deepEqual(p.layers, [], 'the empty-net card must toggle nothing');
  const e = rich.events.find(x => x.per === p.at.per && x.rem === p.at.rem);
  assert.ok(e.sit && (e.sit[0] === '0' || e.sit[3] === '0'),
            `the moment must actually have a goalie pulled, and sit is ${e && e.sit}`);
});

test('the closing sentence counts the cards it is standing next to', () => {
  // PROSE THAT REFERS TO ANOTHER ELEMENT BY COUNT has a dependency nothing in a
  // text file can see, and this page has already broken exactly that way once.
  const note = /<p class="cnote">([\s\S]*?)<\/p>/.exec(html)[1];
  const total = Number(/These (\d+) moments/.exec(note)[1]);
  const first = Number(/and (\d+) of them/.exec(note)[1]);
  assert.equal(total, cards.length, 'the sentence must count the cards on the page');
  const inP1 = Object.values(built.doors).filter(d => d.per === 1).length;
  assert.equal(first, inP1, 'and the first-period claim must be the real one');
});

test('the two groups stay apart, and the measurements are the marked half', () => {
  // The split is the page's argument -- the league's rules against our
  // arithmetic -- and a uniform grid would flatten two kinds of claim into one.
  assert.match(html, /class="grid learn rules"/);
  assert.match(html, /class="grid learn ours"/);

  // NOT "a border-left exists" -- that passed while the accent was set to the
  // same colour as every other card's edge, which is no distinction at all. The
  // property is that the marked group differs, and that it differs USING THE
  // TOKEN THAT ALREADY MEANS "our claim" on this site, so a reader meets a
  // marker they have seen on `.limits` rather than a new one.
  const accent = /\.grid\.learn\.ours \.card\{border-left:[^}]*?(var\(--[a-z]+\))\}/.exec(html);
  assert.ok(accent, 'the measurement group must carry its own left edge');
  const limits = /\.limits li\{[^}]*?border-left:[^;]*?(var\(--[a-z]+\))/.exec(html);
  assert.ok(limits, 'the .limits accent should still be there to agree with');
  assert.equal(accent[1], limits[1],
               'the measurement group must reuse the token that already means "our claim"');
  const edge = /(?<!\.grid\.learn\.ours )\.card\{[^}]*?border:1px solid (var\(--[a-z]+\))/.exec(html);
  assert.notEqual(accent[1], edge && edge[1],
                  'an accent the same colour as the default edge distinguishes nothing');
});

test('the doors document is what the layers currently say', () => {
  // The committed JSON is a build artifact, and a stale one would let the page
  // and the layers disagree silently. npm run build:check diffs it; this proves
  // the regeneration is deterministic and driven by the real reducers.
  assert.deepEqual(doors(rich), built);
});

test('a card with no door fails the build rather than rendering a dead link', () => {
  // The seam between two documents keyed by a shared set of ids. Proven by
  // asking the generator for a game it cannot serve every card from.
  const stripped = { ...rich, events: rich.events.filter(e => e.rsn !== 'icing') };
  assert.throws(() => doors(stripped), /icing/,
                'a game with no icing must refuse to produce doors, not emit a broken one');
});

/* ═══ THE TRIP BACK — the work panel links to the card that explains it ═══
 *
 * Kevin: *"aligning show me the work with learning cards, and making them
 * bi-directional."* The forward half has existed since the doors shipped. The
 * return half did not, and could not: before this, `what-you-can-see.html`
 * carried **zero elements with an id**, so there was nothing on it to link to.
 */

test('⭐ every card is anchored, and its anchor IS its door key', () => {
  // A card with no id is a dead link from the game; a card whose id is not the
  // key `doors` uses is a link to the wrong lesson — and both render fine.
  assert.equal(cards.length, Object.keys(built.doors).length);
  for (const c of cards)
    assert.ok(c.id in built.doors,
      `the card "${c.title}" is anchored #${c.id}, which is not a door key`);
  assert.equal(new Set(cards.map(c => c.id)).size, cards.length,
    'two cards share an anchor, so one of them is unreachable');
});

test('⭐ the app’s LEARNCARDS map is DERIVED, not a third copy of the pairing', () => {
  /* THE FAILURE THIS EXISTS FOR: the pairing is now stated in three places —
     `doors[].layers` (written by node from the real reducers), `LEARN_CARDS`
     (the titles), and the constant inlined into the bundle. A hand-written
     third copy is a cache of the other two, and a stale link still LOOKS like a
     link. So the bundle's map is re-derived here from the two sources and
     compared byte for byte with what shipped. */
  const app = readFileSync(new URL('../src/read-the-game.html', import.meta.url), 'utf8');
  const m = /const LEARNCARDS = (\{.*?\});/.exec(app);
  assert.ok(m, 'the app no longer carries a learn-card map at all');
  const shipped = JSON.parse(m[1]);

  const title = Object.fromEntries(cards.map(c => [c.id, c.title]));
  const want = {};
  for (const cid of Object.keys(built.doors).sort())
    for (const layer of built.doors[cid].layers)
      (want[layer] ||= []).push({ id: cid, title: title[cid] });
  assert.deepEqual(shipped, want,
    'the inlined map disagrees with the doors and the card titles it is made of');

  // AND IT IS NOT EMPTY, or the comparison above is two empties agreeing.
  assert.ok(Object.keys(shipped).length >= 4, `only ${Object.keys(shipped).length} layers carry a card`);
  assert.deepEqual(shipped.whistle.map(c => c.id).sort(),
    ['faceoffs', 'icing', 'offside', 'penalties'],
    'Stoppages is taught by four cards; listing one would be choosing inside a set the data does not rank');
});

test('⚠️ the Blocked layer has no card, and the row is ABSENT rather than empty', () => {
  /* A REAL CONTENT GAP, PINNED SO IT IS NOT MISTAKEN FOR A BUG. The card called
     "blocked" opens the ATTEMPTS layer — its door is the first blocked shot the
     Control reducer counts — so the Blocked layer itself is taught by nothing.
     An empty "Learn More" row would advertise the gap; no row says nothing,
     which is true. When a Blocked card is written this test should fail, and
     the fix is to delete it. */
  const app = readFileSync(new URL('../src/read-the-game.html', import.meta.url), 'utf8');
  const shipped = JSON.parse(/const LEARNCARDS = (\{.*?\});/.exec(app)[1]);
  assert.ok(!shipped.blocked, 'a Blocked card now exists — delete this test');
  assert.match(app, /function cardsFor\(id\)\{const cs=LEARNCARDS\[id\];\s*\n?\s*if\(!cs\|\|!cs\.length\)return '';/,
    'the panel no longer refuses to draw a row for a layer with no cards');
});

test('⭐ the Learn More row is BELOW the ledger, never beside the arithmetic', () => {
  /* KEVIN'S CALL, and the reason it is worth pinning: this panel is a
     VERIFICATION surface. The link is the only thing in it that is not
     evidence, so a reader auditing a count must reach the arithmetic first and
     meet the invitation after it closes. Moved above the ledger the panel stops
     leading with its evidence — and nothing else in the suite would notice. */
  // ⚠️ NOT a non-greedy match from `$('workBody').innerHTML=` — that stops at
  // the EARLY RETURN (`innerHTML='';return;}`) a hundred lines up, so the test
  // read a two-character string and reported the panel had lost its footer.
  // These two strings each occur once in the bundle; their order is the claim.
  const app = readFileSync(new URL('../src/read-the-game.html', import.meta.url), 'utf8');
  const foot = app.indexOf('class="wfoot"');
  const learn = app.indexOf('+cardsFor(id);');
  assert.ok(foot > 0 && learn > 0, 'the panel no longer has both a footer and a learn row');
  assert.ok(learn > foot,
    'the Learn More row is being emitted before the conservation line it must follow');
});

test('the anchor a card is landed on is not flush with the viewport edge', () => {
  // Only ever consumed on a `#hash` arrival, which is now the whole point of
  // the card carrying an id.
  const page = readFileSync(new URL('../src/what-you-can-see.html', import.meta.url), 'utf8');
  assert.match(page, /scroll-margin-top:\s*16px/,
    'a card arrived at by anchor parks flush against the top edge again');
});
