/**
 * The health line, generated instead of typed.
 *
 * WHY THIS EXISTS. `docs/status.md` opened with a line reading "4,553 archived ·
 * 4,417 published · 136 refused · 567 JS + 130 Python tests", and every one of
 * those numbers was wrong within a day of being written — twice over. It even
 * carried a warning saying so, which is a disclaimer where an invariant belongs.
 * A number a human retypes is a number that drifts, and this one sits at the top
 * of the file we read first, so its drift propagates into everything decided
 * from it. Tracked as C9, and it made its own case three times in 48 hours.
 *
 * TWO HALVES, AND THEY ARE KNOWABLE IN DIFFERENT PLACES.
 *
 *   the suite     countable from this repo, offline, by running it. Written
 *                 into the block here and CHECKED by `npm run health --check`,
 *                 which the gates run after the suite they just counted.
 *   the archive   only the published ledger knows it, and it changes nightly
 *                 with no deploy. Fetched when the network is there, and
 *                 STAMPED with when — because a figure with no date is the
 *                 thing that misleads, not a figure that is a day old.
 *
 * The block is delimited so nothing else in the document is touched, and a
 * human's prose above and below it survives regeneration.
 *
 *   node builders/health.mjs            rewrite the block
 *   node builders/health.mjs --check    fail if the block is stale (no network)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { join, dirname } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOC = join(ROOT, 'docs', 'status.md');
const OPEN = '<!-- health: generated by builders/health.mjs — do not edit -->';
const SHUT = '<!-- /health -->';

/**
 * Run the suites and read their own totals, rather than counting `test(` lines.
 *
 * THE COMMANDS ARE READ FROM package.json, NEVER RETYPED HERE, and the first
 * version of this file proves why: it ran `node --test test/` where `npm test`
 * runs `node --test test/*.test.js`, and reported 609 against the suite's 608.
 * A gate comparing a number to a DIFFERENT suite's number is worse than no gate
 * — it fails for a reason nobody can act on, or passes while both drift.
 *
 * stderr is captured for both. `unittest` writes "Ran N tests" to stderr, and
 * reading only stdout gave a confident `NaN` in the generated line.
 */
export function suiteCounts() {
  const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).scripts;
  const run = cmd => execFileSync('sh', ['-c', `${cmd} 2>&1`], {
    cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'],
    maxBuffer: 1 << 26 });
  const js = run(pkg.test);
  const py = run(pkg['test:py']);
  const num = (out, re) => { const m = out.match(re); return m ? Number(m[1]) : null; };
  return {
    js: num(js, /^# pass (\d+)$/m),
    jsFail: num(js, /^# fail (\d+)$/m),
    py: num(py, /^Ran (\d+) tests?/m),
  };
}

/** The published ledger, or null when there is no network. Never invented. */
async function ledger() {
  try {
    const r = await fetch(`https://data.readthegame.co/index.json?cb=${Date.now()}`,
                          { signal: AbortSignal.timeout(20000) });
    if (!r.ok) return null;
    const e = (await r.json()).extracts;
    return e && { games: e.games, published: e.published, refused: e.refused,
                  unreconciled: e.unreconciled, asOf: e.asOf };
  } catch { return null; }
}

const n = v => v == null ? '—' : v.toLocaleString('en-US');

export function block(counts, live, stamp) {
  const suite = `**${n(counts.js)} JS + ${n(counts.py)} Python tests**`;
  // NO NETWORK IS A STATE, NOT A ZERO. "We could not ask" and "the archive is
  // empty" are different sentences and only one of them is alarming.
  const arch = live
    ? `${n(live.games)} archived · **${n(live.published)} published** · `
      + `${n(live.refused)} refused · ${n(live.unreconciled)} unreconciled`
    : '_archive not read — this block was regenerated without network_';
  return [OPEN,
    `**Health right now:** ${arch} · ${suite}`,
    '',
    live
      ? `<sub>Generated ${stamp} by \`node builders/health.mjs\`. Archive figures `
        + `from the published ledger, whose own \`asOf\` is ${live.asOf}; the `
        + `nightly moves them with no deploy, so re-run before quoting. Suite `
        + `counts are checked by \`npm run gates\` and cannot go stale silently.</sub>`
      : `<sub>Generated ${stamp} by \`node builders/health.mjs\`, offline.</sub>`,
    SHUT].join('\n');
}

function splice(doc, made) {
  const a = doc.indexOf(OPEN), b = doc.indexOf(SHUT);
  if (a === -1 || b === -1) throw new Error('the health block markers are missing from docs/status.md');
  return doc.slice(0, a) + made + doc.slice(b + SHUT.length);
}

/* ⭐ NOTHING RUNS ON IMPORT, AND THIS FILE TAUGHT ME WHY THE HARD WAY.
   `suiteCounts()` shells out to `npm test`. With the work at top level, a test
   importing `block` from here ran the whole suite, which ran that test, which
   ran the suite — the check never returned and there was nothing on screen to
   say what it was doing. A module that DOES something when you import it cannot
   be tested by the thing it does. */
if (import.meta.url === pathToFileURL(process.argv[1] || '').href) main();

async function main() {
const check = process.argv.includes('--check');
const doc = readFileSync(DOC, 'utf8');
const counts = suiteCounts();

if (check) {
  // OFFLINE ON PURPOSE. This runs inside `npm run gates`, and a gate that needs
  // the network fails for reasons that are not about the code — the same rule
  // that keeps the unit tests off the wire. It checks the half the repo owns.
  const said = doc.match(/\*\*([\d,]+) JS \+ ([\d,]+) Python tests\*\*/);
  if (!said) { console.error('::error::docs/status.md has no health line'); process.exit(1); }
  const [, js, py] = said;
  const ok = js === n(counts.js) && py === n(counts.py);
  if (!ok) {
    console.error(`::error::docs/status.md says ${js} JS + ${py} Python tests; the suite `
      + `just reported ${n(counts.js)} + ${n(counts.py)}. Run \`node builders/health.mjs\`.`);
    process.exit(1);
  }
  console.log(`  health line agrees with the suite: ${n(counts.js)} JS + ${n(counts.py)} Python`);
} else {
  const live = await ledger();
  const stamp = new Date().toISOString().slice(0, 10);
  writeFileSync(DOC, splice(doc, block(counts, live, stamp)));
  console.log(`  health block rewritten: ${n(counts.js)} JS + ${n(counts.py)} Python`
    + (live ? `, ${n(live.published)} published of ${n(live.games)}` : ', archive not read'));
  if (counts.jsFail) console.log(`  ⚠️  ${counts.jsFail} JS tests are FAILING`);
}
}
