/**
 * The archive-snapshot banner, on every design document that quotes a figure
 * the archive has since moved past.
 *
 * ⚠️⚠️ WHY THIS IS A BANNER AND NOT AN EDIT. Eighteen documents quote figures
 * from the derive run that was current when they were written — 4,119 games,
 * 54.5%, 3,855, 51.9%. Every one was correct on the day. Rewriting them to
 * today's values would be the obvious move and it is WRONG: these are dated
 * arguments, the numbers are the evidence the argument was made from, and
 * silently updating them would make the record claim a case was argued from
 * evidence nobody had yet. The measurement is not the defect; an undated
 * measurement read as a current one is.
 *
 * So the body is never touched. A generated block says which run it came from
 * and what the figures are NOW, and the reader is told which is which.
 *
 * ⭐ AND THE BANNER ITSELF CANNOT GO STALE, which is the whole reason it is
 * generated. Its current figures are read from `data/measures.json` — the same
 * file the site publishes and a reader can fetch — so a re-derive moves all
 * eighteen at once and `--check` fails until it has. A hand-written "the
 * archive is now N" line would be the third generation of exactly the defect
 * being fixed here.
 *
 *   node tools/snapshots.mjs            write/refresh every banner
 *   node tools/snapshots.mjs --check    fail if one is missing or stale
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const ROOT = new URL('..', import.meta.url).pathname;
const DOCS = join(ROOT, 'docs');
const OPEN = '<!-- snapshot: generated by tools/snapshots.mjs — do not edit -->';
const SHUT = '<!-- /snapshot -->';

/**
 * Figures the archive has moved past. HISTORICAL VALUES, so this list is safe
 * to hold as a constant — the one kind of number that cannot drift is one that
 * has already been superseded. The CURRENT values are never written here; they
 * come from measures.json below.
 */
export const SUPERSEDED = [
  '4,119', '4,029', '3,957', '3,855', '4,417',   // populations
  '54.5%', '45.8%', '39.6%',                     // the three base rates
  '1,527', '51.9%', '27.8%', '491,971',          // counts and the attempt mix
];

/**
 * ⛔ NOT ARTIFACTS, AND EXEMPT FOR STATED REASONS.
 *   README.md   the index — it quotes these figures while EXPLAINING the
 *               convention, so banner-ing it would be circular.
 *   status.md   the living build list, not a dated argument. Its one citation
 *               names the old and new values side by side deliberately.
 */
const EXEMPT = new Set(['README.md', 'status.md']);

/** game-sentence.md carries a better, hand-written correction table. */
const HAND_WRITTEN = /EVERY FIGURE BELOW IS FROM AN ARCHIVE/;

export function figures() {
  const m = JSON.parse(readFileSync(join(ROOT, 'data', 'measures.json'), 'utf8'));
  const n = v => v.toLocaleString('en-US');
  const pc = r => `${(r.rate * 100).toFixed(1)}%`;
  const b = m.baseRates;
  return { measured: n(m.measured),
           att: `${pc(b.moreAttemptsLost)} of ${n(b.moreAttemptsLost.n)}`,
           sog: `${pc(b.moreShotsOnGoalLost)} of ${n(b.moreShotsOnGoalLost.n)}`,
           lvl: `${pc(b.moreLevelControlLost)} of ${n(b.moreLevelControlLost.n)}` };
}

export function banner(f) {
  return [OPEN,
    '> 📅 **ARCHIVE SNAPSHOT.** This document quotes archive figures from the derive',
    '> run that was current when it was written, and they are the evidence its',
    `> argument was made from. **The archive now holds ${f.measured} measured games**, and`,
    `> the three base rates are **${f.att}** (the team with more shot attempts lost),`,
    `> **${f.sog}** (more shots on goal) and **${f.lvl}** (more control while the score`,
    '> was level). The body below is left exactly as it was argued — see',
    '> [README.md](README.md) on why a measurement here is dated rather than updated.',
    SHUT].join('\n');
}


/**
 * A document with its GENERATED blocks removed.
 *
 * ⚠️ WRITTEN BECAUSE THIS CHECKER DEMANDED AN ARCHIVE BANNER ON A DOCUMENT THAT
 * QUOTES NO ARCHIVE FIGURE. `architecture.md`'s tier table is counted from the
 * filesystem, and on 2026-09-04 the presentation tier came to 3,957 lines —
 * which is also a retired archive population in the list above. The scan matches
 * a bare number with no context, so a line count collided with a figure and the
 * gate asked for a banner saying the document quotes stale archive data.
 *
 * ⭐ THE RULE THIS EARNS IS GENERAL: a generated block cannot QUOTE anything. Its
 * numbers are derived by a tool from the tree at build time, so they carry no
 * claim about the archive and cannot go stale in the way a banner is for. Prose
 * checks belong on prose, and this is where the two are separated.
 *
 * Any `<!-- name: … -->` / `<!-- /name -->` pair, so a document that gains a new
 * generated block is covered without this list being edited.
 */
const prose = t => t.replace(/<!--\s*([a-z-]+):[\s\S]*?<!--\s*\/\1\s*-->/g, ' ');

/** Documents that quote a superseded figure and are not exempt. */
export function needing() {
  return readdirSync(DOCS)
    .filter(f => f.endsWith('.md') && !EXEMPT.has(f))
    .filter(f => {
      const t = prose(readFileSync(join(DOCS, f), 'utf8'));
      return SUPERSEDED.some(s => t.includes(s)) && !HAND_WRITTEN.test(t);
    })
    .sort();
}

function splice(doc, made) {
  const a = doc.indexOf(OPEN), b = doc.indexOf(SHUT);
  if (a !== -1 && b !== -1) return doc.slice(0, a) + made + doc.slice(b + SHUT.length);
  // Not present: insert directly under the H1, above any other banner, so the
  // placement is the same in every document and this stays idempotent.
  const lines = doc.split('\n');
  if (!lines[0].startsWith('# ')) throw new Error('document does not open with an H1');
  return [lines[0], '', made, ...lines.slice(1)].join('\n');
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) main();

function main() {
  const f = figures(), want = banner(f), files = needing();
  if (process.argv.includes('--check')) {
    const bad = files.filter(name => {
      const t = readFileSync(join(DOCS, name), 'utf8');
      return !t.includes(want);   // absent, or present with figures that moved
    });
    if (bad.length) {
      console.error(`::error::these documents quote a superseded archive figure and their `
        + `snapshot banner is missing or stale — ${bad.join(', ')}. `
        + 'Run `node tools/snapshots.mjs`.');
      process.exit(1);
    }
    console.log(`  archive-snapshot banners current on ${files.length} documents`);
  } else {
    for (const name of files) {
      const p = join(DOCS, name);
      writeFileSync(p, splice(readFileSync(p, 'utf8'), want));
    }
    console.log(`  snapshot banner written to ${files.length} documents `
      + `(archive now ${f.measured} games)`);
  }
}
