/**
 * The tier table in docs/architecture.md, counted rather than typed.
 *
 * ⚠️⚠️ WRITTEN BECAUSE THE TABLE IT REPLACES WAS WRONG IN EVERY ROW. Dated
 * 2026-08-11, `docs/architecture.md` opened with sizes for five tiers. Three
 * weeks later `extract.py` had gone 459 → 856, `derive.py` 393 → 728, and the
 * analysis tier — the row the whole document argues from — said 1,065 against an
 * actual 5,469. **Off by 5.1× on its own central figure**, in the one file a
 * reader opens first to learn the shape of the system.
 *
 * That is the defect this repo already named for `docs/status.md` and fixed the
 * same way: *the build list is a cache of the code*. A number a human retypes is
 * a number that drifts, and a description of the architecture that is wrong
 * about the architecture is worse than no description, because it is read with
 * trust.
 *
 * ⭐ IT COUNTS FILES, NOT CLAIMS. Sizes are mechanical and belong to a tool; what
 * each tier IS and why the boundary sits there is prose, written by a person,
 * and lives outside the block. The markers keep the two apart so regenerating
 * this never touches an argument.
 *
 *   node tools/tiers.mjs            rewrite the block
 *   node tools/tiers.mjs --check    fail if it is stale
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const ROOT = new URL('..', import.meta.url).pathname;
const DOC = join(ROOT, 'docs', 'architecture.md');
const OPEN = '<!-- tiers: generated by tools/tiers.mjs — do not edit -->';
const SHUT = '<!-- /tiers -->';

const lines = p => readFileSync(join(ROOT, p), 'utf8').split('\n').length;

/** Every file under a directory matching an extension, recursively. */
function walk(dir, ext, out = []) {
  for (const e of readdirSync(join(ROOT, dir))) {
    const rel = `${dir}/${e}`;
    if (statSync(join(ROOT, rel)).isDirectory()) walk(rel, ext, out);
    else if (e.endsWith(ext)) out.push(rel);
  }
  return out;
}

const sum = fs => fs.reduce((n, f) => n + lines(f), 0);

/**
 * ⭐ THE TIERS ARE NAMED HERE AND COUNTED FROM THE FILESYSTEM. A tier whose
 * glob stops matching reports zero rather than quietly reporting its old
 * number — which is the failure mode of the table this replaces.
 */
export function tiers() {
  const builders = walk('builders', '.py').filter(f => /\/build_/.test(f));
  const lib = walk('src/lib', '.js');
  return [
    { tier: 'acquisition', does: 'talks to the league, stores bytes',
      where: '`fetch_nhl.py`', n: lines('builders/fetch_nhl.py') },
    { tier: 'interpretation', does: 'feed → events; the two gates',
      where: '`extract.py`', n: lines('builders/extract.py') },
    { tier: 'orchestration', does: 'walks the store, judges, writes documents',
      where: '`derive.py`', n: lines('builders/derive.py') },
    { tier: 'analysis', does: 'events → meaning; pure, no DOM, no network',
      where: `\`src/lib/**\` (${lib.length} modules)`, n: sum(lib) },
    { tier: 'measurement', does: 'the archive, reduced by the SAME modules',
      where: '`measure.mjs`', n: lines('builders/measure.mjs') },
    { tier: 'presentation', does: 'generates the pages',
      where: `\`build_*.py\` (${builders.length})`, n: sum(builders) },
    { tier: 'the app', does: '**the one exception — see §2**',
      where: '`src/app.js`', n: lines('src/app.js') },
  ];
}

/**
 * Source with comments removed.
 *
 * ⚠️⚠️ THE FIRST VERSION OF `facts()` DID NOT DO THIS AND PUBLISHED A FALSE
 * CLAIM. It tested the raw text for `\bdocument\b`, which matches the English
 * word — `measure.mjs` "writes one document", `layer.js` "a document nobody is
 * alerted by" — so it reported TEN of the twenty-six analysis modules as
 * reaching outside pure computation and printed "the boundary §1 claims is
 * broken" into a generated block. Every one was prose.
 *
 * That is this repo's dominant failure mode arriving in the instrument built to
 * describe it: **a check built from a sloppy model of its input**, going green
 * (or in this case red) with total confidence. It is also why the purity claim
 * is COUNTED here rather than asserted in the prose — but a counter that reads
 * comments is not counting code.
 */
const code = src => src
  .replace(/\/\*[\s\S]*?\*\//g, ' ')
  .replace(/^\s*\/\/.*$/gm, ' ');

/** The properties §1 claims, verified rather than asserted. */
export function facts() {
  const lib = walk('src/lib', '.js');
  /* Real reaches outside pure computation: member access on a host object, a
     network call, or an import of a runtime module. Not the words for them. */
  const REACH = /(\bdocument\s*\.|\bwindow\s*\.|\blocalStorage\b|\bgetElementById\b|\bfetch\s*\(|\bXMLHttpRequest\b|from\s*['"]node:|\brequire\s*\()/;
  const impure = lib.filter(f => REACH.test(code(readFileSync(join(ROOT, f), 'utf8'))));
  const app = readFileSync(join(ROOT, 'src/app.js'), 'utf8');
  /* ⚠️ THIS BLOCK USED TO PUBLISH A BINDING COUNT, AND IT WAS WRONG TWICE OVER.
     `^(let|var) ` finds declarations at column zero, which inside a 3,300-line
     function is an arbitrary subset -- it reported 24 where a hand audit of every
     site found 25 -- and it called them "module-level" when every one of them is
     a LOCAL of `boot`. A number a scanner cannot get right does not belong in a
     generated block; it belongs in §2's prose with the audit that produced it.

     What replaces it is what a tool can stand behind, and it is also the fact
     that changed: since 2026-09-04 `src/app.js` is a module, so its dependencies
     on the analysis tier are DECLARED rather than resolved by concatenation.
     `test/app-imports.test.js` is what keeps that list honest. */
  return {
    libModules: lib.length,
    impure: impure.map(f => f.replace('src/lib/', '')),
    appImports: (code(app).match(/^import\b/gm) || []).length,
    appExports: (code(app).match(/^export\b/gm) || []).length,
    ...shape(app),
  };
}

/**
 * How much of `src/app.js` is prose about itself — §2's central figure.
 *
 * WRITTEN BECAUSE IT WAS TYPED BY HAND THREE TIMES AND DRIFTED EVERY TIME, into a
 * document whose own header says no number in it is typed by hand. Every edit to
 * that file moves these, so they are counted here or they are wrong.
 *
 * Whole lines, and deliberately the conservative reading: a line of code with a
 * trailing comment counts as CODE. That understates the prose rather than
 * flattering the argument section 2 makes with it.
 */
function shape(src) {
  const rows = src.split('\n');
  let comment = 0, blank = 0, block = false;
  for (const line of rows) {
    const t = line.trim();
    if (!t) { blank++; continue; }
    if (block) { comment++; if (t.includes('*/')) block = false; continue; }
    if (t.startsWith('//')) { comment++; continue; }
    if (t.startsWith('/*')) { comment++; if (!t.includes('*/')) block = true; continue; }
  }
  return {
    appLines: rows.length, appComment: comment, appCode: rows.length - comment - blank,
    appClaims: rows.filter(l => /\u2b50|\u26a0\ufe0f|\u26d4/.test(l)).length,
  };
}

export function block(t, f, stamp) {
  const w = ['| tier | what it does | where it lives | lines |',
             '|---|---|---|---|'];
  for (const r of t) w.push(`| **${r.tier}** | ${r.does} | ${r.where} | ${r.n.toLocaleString('en-US')} |`);
  return [OPEN, ...w, '',
    `<sub>Counted ${stamp} by \`tools/tiers.mjs\`, checked by \`npm run gates\`. `
    + `The analysis tier is **${f.libModules} modules** and `
    + (f.impure.length
        ? `**${f.impure.join(', ')} reach outside pure computation** — the boundary §1 claims is broken.`
        : `**not one of them touches the DOM, the network or the filesystem** — `
          + `the boundary §1 claims, verified here rather than asserted.`)
    + ` \`src/app.js\` **declares ${f.appImports} dependencies on that tier and exports `
    + `${f.appExports === 1 ? '1 function' : `${f.appExports} names`}** — it is a module, `
    + `not a build template, and §2 is what remains. Of its ${f.appLines.toLocaleString('en-US')} `
    + `lines **${f.appComment.toLocaleString('en-US')} are comment-only and ${f.appCode} are code**, `
    + `and **${f.appClaims} comment lines carry an explicit claim** about the code beside them — `
    + `which is §2's argument, counted rather than asserted.</sub>`,
    SHUT].join('\n');
}

function splice(doc, made) {
  const a = doc.indexOf(OPEN), b = doc.indexOf(SHUT);
  if (a === -1 || b === -1)
    throw new Error('the tier block markers are missing from docs/architecture.md');
  return doc.slice(0, a) + made + doc.slice(b + SHUT.length);
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) main();

function main() {
  const doc = readFileSync(DOC, 'utf8');
  const t = tiers(), f = facts();
  if (process.argv.includes('--check')) {
    /* ⭐ IT COMPARES THE TABLE, NOT A STAMP. A date tells you when somebody ran
       this; only the numbers tell you whether they are still true.
       ⚠️ AND IT USED TO COMPARE ONLY THE ROWS, which was fine until the block
       gained a sentence. The moment `facts()` started publishing app.js's comment
       and claim counts, those were generated, printed, read with trust — and
       unchecked, because the loop below only ever knew about tiers. A generated
       figure nothing verifies is a hand-typed figure with better manners. So the
       WHOLE block is compared now, with the stamp masked out of both sides. */
    const here = doc.slice(doc.indexOf(OPEN), doc.indexOf(SHUT) + SHUT.length);
    const mask = b => b.replace(/Counted \d{4}-\d{2}-\d{2} by/, 'Counted <date> by');
    if (mask(here) !== mask(block(t, f, '0000-00-00'))) {
      /* Name the first line that differs: "the block is stale" sends a reader to
         diff two paragraphs by eye. */
      const A = mask(here).split('\n'), B = mask(block(t, f, '0000-00-00')).split('\n');
      const i = A.findIndex((l, n) => l !== B[n]);
      console.error("::error::docs/architecture.md's generated block is stale. "
        + 'Run `node tools/tiers.mjs`.');
      /* A WINDOW ON THE DIVERGENCE, not the first 160 characters. The generated
         sub-line is one long paragraph, so printing its head showed two identical
         strings and told a reader nothing — the first version of this message did
         exactly that. Skip the shared prefix, then show what follows. */
      const a = A[i] ?? '', c = B[i] ?? '';
      let j = 0; while (j < a.length && j < c.length && a[j] === c[j]) j++;
      const from = Math.max(0, j - 30);
      console.error(`    doc: …${a.slice(from, from + 140)}…`);
      console.error(`    now: …${c.slice(from, from + 140)}…`);
      process.exit(1);
    }
    console.log(`  architecture block agrees with the tree (${t.length} tiers, `
      + `${f.libModules} analysis modules)`);
  } else {
    writeFileSync(DOC, splice(doc, block(t, f, new Date().toISOString().slice(0, 10))));
    console.log(`  tier table rewritten: ${t.length} tiers, ${f.libModules} analysis modules, `
      + `${f.impure.length} impure`);
  }
}
